/********************************************************************************
** Form generated from reading UI file 'projectdetails.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROJECTDETAILS_H
#define UI_PROJECTDETAILS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ProjectDetails
{
public:
    QTabWidget *tabWidget;
    QWidget *tbGeneral;
    QPushButton *cmdLocationDel;
    QPushButton *cmdLocationAdd;
    QListWidget *lstLocations;
    QComboBox *cbGenre;
    QSpinBox *sbRuntime;
    QComboBox *cbLanguage;
    QPushButton *cmdClearGeneralChanges;
    QLineEdit *txtLocationAdd;
    QLabel *lblRuntime;
    QLabel *lblSummary;
    QLabel *lblLocations;
    QSpinBox *sbSales;
    QDateEdit *deRelease;
    QComboBox *cbStatus;
    QPushButton *cmdApplyGeneralChanges;
    QLabel *lblGenre;
    QLabel *lblStatus;
    QLabel *lblRelease;
    QTextEdit *txtSummary;
    QLineEdit *txtTitleProject;
    QLabel *lblTitleProjects;
    QLabel *lblLanguage;
    QLabel *lblKeywords;
    QLabel *lblSales;
    QListWidget *lstKeywords;
    QLineEdit *txtKeywordsAdd;
    QPushButton *cmdKeywordsDel;
    QPushButton *cmdKeywordsAdd;
    QWidget *tbCrew;
    QLineEdit *txtCrew;
    QListWidget *lstCrew;
    QPushButton *cmdCrewFilter;
    QComboBox *cbCrew;
    QPushButton *cmdCrewDel;
    QPushButton *cmdCrewAdd;
    QLabel *lblDateOfBirth;
    QLabel *lblIDNum;
    QLabel *lblNameTitle;
    QLabel *lblExperience;
    QComboBox *cbNameTitle;
    QLineEdit *txtIDNum;
    QDateEdit *deDofB;
    QSpinBox *sbExperience;
    QLineEdit *txtName;
    QLabel *lblName;
    QListWidget *lstCrewLocations;
    QLabel *lblCrewLocations;
    QWidget *tbMaterials;
    QLabel *lblMaterialType;
    QComboBox *cbMaterialType;
    QLabel *lblMaterialIDNum;
    QLabel *lblMaterialTitle;
    QLabel *lblVFormat;
    QLabel *lblAFormat;
    QLabel *lblMaterialLanguage;
    QLabel *lblMaterialFrameHorizontal;
    QLabel *lblMaterialPackage;
    QLabel *lblMaterialRuntime;
    QLabel *lblMaterialPrice;
    QLabel *lblMaterialSubLang;
    QLineEdit *txtMaterialIDNum;
    QLineEdit *txtMaterialTitle;
    QComboBox *cbVFormat;
    QComboBox *cbAFormat;
    QComboBox *cbMaterialLanguage;
    QListWidget *lstSubLang;
    QComboBox *cbSubLang;
    QPushButton *cmdSubLangAdd;
    QPushButton *cmdSubLangDel;
    QSpinBox *sbMaterialPrice;
    QLabel *lblMaterialCreated;
    QLabel *lblMaterialAnswer;
    QPushButton *cmdMaterialClear;
    QPushButton *cmdMaterialDel;
    QPushButton *cmdMaterialCreate;
    QSpinBox *sbMaterialRuntime;
    QPushButton *cmdExtraLanguageTracksDel;
    QListWidget *lstExtraLanguageTracks;
    QComboBox *cbExtraLanguageTracks;
    QPushButton *cmdExtraLanguageTracksAdd;
    QComboBox *cbExtraSubtitleTracks;
    QPushButton *cmdExtraSubtitleTracksAdd;
    QListWidget *lstExtraSubtitleTracks;
    QPushButton *cmdExtraSubtitleTracksDel;
    QPushButton *cmdBonusFeaturesAdd;
    QListWidget *lstBonusFeatures;
    QPushButton *cmdBonusFeaturesDel;
    QLabel *lblExtraLanguageTracks;
    QLabel *lblExtraSubtitleTracks;
    QLabel *lblBonusFeatures;
    QLabel *lblFirstSideContent;
    QLineEdit *txtFirstSideContent;
    QLabel *lblSecondSideContent;
    QLineEdit *txtSecondSideContent;
    QLineEdit *txtBonusFeatures;
    QSpinBox *sbFrameHorizontal;
    QSpinBox *sbFrameVertical;
    QLabel *lblMaterialFrameVertical;
    QLabel *lblMaterialFrameAspect;
    QLineEdit *txtFrameDescription;
    QLabel *lblMaterialFrameDescription;
    QLabel *lblMaterialPackageMaterial;
    QLabel *lblMaterialPackageHeight;
    QLabel *lblMaterialPackageDepth;
    QSpinBox *sbPackagingHeight;
    QSpinBox *sbPackagingDepth;
    QLabel *lblMaterialPackageWidth;
    QSpinBox *sbPackagingWidth;
    QComboBox *cbPackagingMaterial;
    QSpinBox *sbComboSingleDVD;
    QLabel *lblComboDoubleDVD;
    QSpinBox *sbComboDoubleDVD;
    QLabel *lblComboSingleDVD;
    QLabel *lblProjectName;

    void setupUi(QDialog *ProjectDetails)
    {
        if (ProjectDetails->objectName().isEmpty())
            ProjectDetails->setObjectName(QStringLiteral("ProjectDetails"));
        ProjectDetails->resize(1344, 682);
        tabWidget = new QTabWidget(ProjectDetails);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 50, 1291, 621));
        tbGeneral = new QWidget();
        tbGeneral->setObjectName(QStringLiteral("tbGeneral"));
        cmdLocationDel = new QPushButton(tbGeneral);
        cmdLocationDel->setObjectName(QStringLiteral("cmdLocationDel"));
        cmdLocationDel->setGeometry(QRect(360, 260, 71, 31));
        cmdLocationAdd = new QPushButton(tbGeneral);
        cmdLocationAdd->setObjectName(QStringLiteral("cmdLocationAdd"));
        cmdLocationAdd->setGeometry(QRect(280, 260, 71, 31));
        lstLocations = new QListWidget(tbGeneral);
        lstLocations->setObjectName(QStringLiteral("lstLocations"));
        lstLocations->setGeometry(QRect(10, 310, 421, 101));
        cbGenre = new QComboBox(tbGeneral);
        cbGenre->setObjectName(QStringLiteral("cbGenre"));
        cbGenre->setGeometry(QRect(550, 60, 331, 31));
        sbRuntime = new QSpinBox(tbGeneral);
        sbRuntime->setObjectName(QStringLiteral("sbRuntime"));
        sbRuntime->setGeometry(QRect(100, 180, 331, 31));
        sbRuntime->setMaximum(1000);
        cbLanguage = new QComboBox(tbGeneral);
        cbLanguage->setObjectName(QStringLiteral("cbLanguage"));
        cbLanguage->setGeometry(QRect(550, 110, 331, 31));
        cmdClearGeneralChanges = new QPushButton(tbGeneral);
        cmdClearGeneralChanges->setObjectName(QStringLiteral("cmdClearGeneralChanges"));
        cmdClearGeneralChanges->setGeometry(QRect(10, 440, 421, 61));
        txtLocationAdd = new QLineEdit(tbGeneral);
        txtLocationAdd->setObjectName(QStringLiteral("txtLocationAdd"));
        txtLocationAdd->setGeometry(QRect(10, 260, 261, 31));
        lblRuntime = new QLabel(tbGeneral);
        lblRuntime->setObjectName(QStringLiteral("lblRuntime"));
        lblRuntime->setGeometry(QRect(10, 180, 60, 31));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        lblRuntime->setFont(font);
        lblSummary = new QLabel(tbGeneral);
        lblSummary->setObjectName(QStringLiteral("lblSummary"));
        lblSummary->setGeometry(QRect(10, 60, 81, 31));
        lblSummary->setFont(font);
        lblLocations = new QLabel(tbGeneral);
        lblLocations->setObjectName(QStringLiteral("lblLocations"));
        lblLocations->setGeometry(QRect(10, 220, 91, 31));
        lblLocations->setFont(font);
        sbSales = new QSpinBox(tbGeneral);
        sbSales->setObjectName(QStringLiteral("sbSales"));
        sbSales->setGeometry(QRect(550, 170, 331, 31));
        sbSales->setMaximum(999999999);
        sbSales->setSingleStep(100);
        deRelease = new QDateEdit(tbGeneral);
        deRelease->setObjectName(QStringLiteral("deRelease"));
        deRelease->setGeometry(QRect(100, 130, 331, 31));
        cbStatus = new QComboBox(tbGeneral);
        cbStatus->setObjectName(QStringLiteral("cbStatus"));
        cbStatus->setGeometry(QRect(550, 10, 331, 31));
        cmdApplyGeneralChanges = new QPushButton(tbGeneral);
        cmdApplyGeneralChanges->setObjectName(QStringLiteral("cmdApplyGeneralChanges"));
        cmdApplyGeneralChanges->setGeometry(QRect(460, 440, 421, 61));
        lblGenre = new QLabel(tbGeneral);
        lblGenre->setObjectName(QStringLiteral("lblGenre"));
        lblGenre->setGeometry(QRect(460, 60, 60, 31));
        lblGenre->setFont(font);
        lblStatus = new QLabel(tbGeneral);
        lblStatus->setObjectName(QStringLiteral("lblStatus"));
        lblStatus->setGeometry(QRect(460, 10, 71, 31));
        lblStatus->setFont(font);
        lblRelease = new QLabel(tbGeneral);
        lblRelease->setObjectName(QStringLiteral("lblRelease"));
        lblRelease->setGeometry(QRect(10, 130, 91, 31));
        lblRelease->setFont(font);
        txtSummary = new QTextEdit(tbGeneral);
        txtSummary->setObjectName(QStringLiteral("txtSummary"));
        txtSummary->setGeometry(QRect(100, 60, 331, 51));
        txtTitleProject = new QLineEdit(tbGeneral);
        txtTitleProject->setObjectName(QStringLiteral("txtTitleProject"));
        txtTitleProject->setGeometry(QRect(100, 10, 331, 31));
        lblTitleProjects = new QLabel(tbGeneral);
        lblTitleProjects->setObjectName(QStringLiteral("lblTitleProjects"));
        lblTitleProjects->setGeometry(QRect(10, 10, 51, 31));
        lblTitleProjects->setFont(font);
        lblLanguage = new QLabel(tbGeneral);
        lblLanguage->setObjectName(QStringLiteral("lblLanguage"));
        lblLanguage->setGeometry(QRect(460, 110, 81, 31));
        lblLanguage->setFont(font);
        lblKeywords = new QLabel(tbGeneral);
        lblKeywords->setObjectName(QStringLiteral("lblKeywords"));
        lblKeywords->setGeometry(QRect(460, 220, 91, 31));
        lblKeywords->setFont(font);
        lblSales = new QLabel(tbGeneral);
        lblSales->setObjectName(QStringLiteral("lblSales"));
        lblSales->setGeometry(QRect(460, 170, 81, 31));
        lblSales->setFont(font);
        lstKeywords = new QListWidget(tbGeneral);
        lstKeywords->setObjectName(QStringLiteral("lstKeywords"));
        lstKeywords->setGeometry(QRect(460, 310, 421, 101));
        txtKeywordsAdd = new QLineEdit(tbGeneral);
        txtKeywordsAdd->setObjectName(QStringLiteral("txtKeywordsAdd"));
        txtKeywordsAdd->setGeometry(QRect(460, 260, 261, 31));
        cmdKeywordsDel = new QPushButton(tbGeneral);
        cmdKeywordsDel->setObjectName(QStringLiteral("cmdKeywordsDel"));
        cmdKeywordsDel->setGeometry(QRect(810, 260, 71, 31));
        cmdKeywordsAdd = new QPushButton(tbGeneral);
        cmdKeywordsAdd->setObjectName(QStringLiteral("cmdKeywordsAdd"));
        cmdKeywordsAdd->setGeometry(QRect(730, 260, 71, 31));
        tabWidget->addTab(tbGeneral, QString());
        tbCrew = new QWidget();
        tbCrew->setObjectName(QStringLiteral("tbCrew"));
        txtCrew = new QLineEdit(tbCrew);
        txtCrew->setObjectName(QStringLiteral("txtCrew"));
        txtCrew->setGeometry(QRect(300, 20, 691, 31));
        lstCrew = new QListWidget(tbCrew);
        lstCrew->setObjectName(QStringLiteral("lstCrew"));
        lstCrew->setGeometry(QRect(20, 210, 1191, 341));
        cmdCrewFilter = new QPushButton(tbCrew);
        cmdCrewFilter->setObjectName(QStringLiteral("cmdCrewFilter"));
        cmdCrewFilter->setGeometry(QRect(1010, 20, 201, 31));
        cbCrew = new QComboBox(tbCrew);
        cbCrew->setObjectName(QStringLiteral("cbCrew"));
        cbCrew->setGeometry(QRect(20, 20, 261, 31));
        cmdCrewDel = new QPushButton(tbCrew);
        cmdCrewDel->setObjectName(QStringLiteral("cmdCrewDel"));
        cmdCrewDel->setGeometry(QRect(770, 160, 441, 31));
        cmdCrewAdd = new QPushButton(tbCrew);
        cmdCrewAdd->setObjectName(QStringLiteral("cmdCrewAdd"));
        cmdCrewAdd->setGeometry(QRect(310, 160, 441, 31));
        lblDateOfBirth = new QLabel(tbCrew);
        lblDateOfBirth->setObjectName(QStringLiteral("lblDateOfBirth"));
        lblDateOfBirth->setGeometry(QRect(310, 70, 101, 31));
        lblIDNum = new QLabel(tbCrew);
        lblIDNum->setObjectName(QStringLiteral("lblIDNum"));
        lblIDNum->setGeometry(QRect(20, 160, 41, 31));
        lblNameTitle = new QLabel(tbCrew);
        lblNameTitle->setObjectName(QStringLiteral("lblNameTitle"));
        lblNameTitle->setGeometry(QRect(20, 70, 41, 31));
        lblExperience = new QLabel(tbCrew);
        lblExperience->setObjectName(QStringLiteral("lblExperience"));
        lblExperience->setGeometry(QRect(310, 120, 91, 31));
        cbNameTitle = new QComboBox(tbCrew);
        cbNameTitle->setObjectName(QStringLiteral("cbNameTitle"));
        cbNameTitle->setGeometry(QRect(70, 70, 191, 31));
        txtIDNum = new QLineEdit(tbCrew);
        txtIDNum->setObjectName(QStringLiteral("txtIDNum"));
        txtIDNum->setGeometry(QRect(70, 160, 191, 31));
        deDofB = new QDateEdit(tbCrew);
        deDofB->setObjectName(QStringLiteral("deDofB"));
        deDofB->setGeometry(QRect(420, 70, 191, 31));
        sbExperience = new QSpinBox(tbCrew);
        sbExperience->setObjectName(QStringLiteral("sbExperience"));
        sbExperience->setGeometry(QRect(420, 120, 191, 31));
        txtName = new QLineEdit(tbCrew);
        txtName->setObjectName(QStringLiteral("txtName"));
        txtName->setGeometry(QRect(70, 110, 191, 31));
        lblName = new QLabel(tbCrew);
        lblName->setObjectName(QStringLiteral("lblName"));
        lblName->setGeometry(QRect(20, 110, 60, 31));
        lstCrewLocations = new QListWidget(tbCrew);
        lstCrewLocations->setObjectName(QStringLiteral("lstCrewLocations"));
        lstCrewLocations->setGeometry(QRect(760, 70, 451, 71));
        lblCrewLocations = new QLabel(tbCrew);
        lblCrewLocations->setObjectName(QStringLiteral("lblCrewLocations"));
        lblCrewLocations->setGeometry(QRect(650, 70, 91, 31));
        tabWidget->addTab(tbCrew, QString());
        tbMaterials = new QWidget();
        tbMaterials->setObjectName(QStringLiteral("tbMaterials"));
        lblMaterialType = new QLabel(tbMaterials);
        lblMaterialType->setObjectName(QStringLiteral("lblMaterialType"));
        lblMaterialType->setGeometry(QRect(10, 20, 141, 31));
        cbMaterialType = new QComboBox(tbMaterials);
        cbMaterialType->setObjectName(QStringLiteral("cbMaterialType"));
        cbMaterialType->setGeometry(QRect(140, 20, 691, 31));
        lblMaterialIDNum = new QLabel(tbMaterials);
        lblMaterialIDNum->setObjectName(QStringLiteral("lblMaterialIDNum"));
        lblMaterialIDNum->setGeometry(QRect(10, 70, 111, 31));
        lblMaterialTitle = new QLabel(tbMaterials);
        lblMaterialTitle->setObjectName(QStringLiteral("lblMaterialTitle"));
        lblMaterialTitle->setGeometry(QRect(10, 120, 111, 31));
        lblVFormat = new QLabel(tbMaterials);
        lblVFormat->setObjectName(QStringLiteral("lblVFormat"));
        lblVFormat->setGeometry(QRect(10, 170, 111, 31));
        lblAFormat = new QLabel(tbMaterials);
        lblAFormat->setObjectName(QStringLiteral("lblAFormat"));
        lblAFormat->setGeometry(QRect(10, 220, 111, 31));
        lblMaterialLanguage = new QLabel(tbMaterials);
        lblMaterialLanguage->setObjectName(QStringLiteral("lblMaterialLanguage"));
        lblMaterialLanguage->setGeometry(QRect(280, 170, 111, 31));
        lblMaterialFrameHorizontal = new QLabel(tbMaterials);
        lblMaterialFrameHorizontal->setObjectName(QStringLiteral("lblMaterialFrameHorizontal"));
        lblMaterialFrameHorizontal->setGeometry(QRect(920, 370, 191, 31));
        lblMaterialPackage = new QLabel(tbMaterials);
        lblMaterialPackage->setObjectName(QStringLiteral("lblMaterialPackage"));
        lblMaterialPackage->setGeometry(QRect(920, 70, 111, 31));
        lblMaterialRuntime = new QLabel(tbMaterials);
        lblMaterialRuntime->setObjectName(QStringLiteral("lblMaterialRuntime"));
        lblMaterialRuntime->setGeometry(QRect(280, 120, 111, 31));
        lblMaterialPrice = new QLabel(tbMaterials);
        lblMaterialPrice->setObjectName(QStringLiteral("lblMaterialPrice"));
        lblMaterialPrice->setGeometry(QRect(280, 70, 101, 31));
        lblMaterialSubLang = new QLabel(tbMaterials);
        lblMaterialSubLang->setObjectName(QStringLiteral("lblMaterialSubLang"));
        lblMaterialSubLang->setGeometry(QRect(530, 70, 131, 31));
        txtMaterialIDNum = new QLineEdit(tbMaterials);
        txtMaterialIDNum->setObjectName(QStringLiteral("txtMaterialIDNum"));
        txtMaterialIDNum->setEnabled(true);
        txtMaterialIDNum->setGeometry(QRect(120, 70, 141, 31));
        txtMaterialIDNum->setReadOnly(true);
        txtMaterialTitle = new QLineEdit(tbMaterials);
        txtMaterialTitle->setObjectName(QStringLiteral("txtMaterialTitle"));
        txtMaterialTitle->setGeometry(QRect(120, 120, 141, 31));
        cbVFormat = new QComboBox(tbMaterials);
        cbVFormat->setObjectName(QStringLiteral("cbVFormat"));
        cbVFormat->setGeometry(QRect(120, 170, 141, 31));
        cbAFormat = new QComboBox(tbMaterials);
        cbAFormat->setObjectName(QStringLiteral("cbAFormat"));
        cbAFormat->setGeometry(QRect(120, 220, 141, 31));
        cbMaterialLanguage = new QComboBox(tbMaterials);
        cbMaterialLanguage->setObjectName(QStringLiteral("cbMaterialLanguage"));
        cbMaterialLanguage->setGeometry(QRect(370, 170, 141, 31));
        lstSubLang = new QListWidget(tbMaterials);
        lstSubLang->setObjectName(QStringLiteral("lstSubLang"));
        lstSubLang->setGeometry(QRect(530, 150, 361, 101));
        cbSubLang = new QComboBox(tbMaterials);
        cbSubLang->setObjectName(QStringLiteral("cbSubLang"));
        cbSubLang->setGeometry(QRect(530, 110, 201, 31));
        cmdSubLangAdd = new QPushButton(tbMaterials);
        cmdSubLangAdd->setObjectName(QStringLiteral("cmdSubLangAdd"));
        cmdSubLangAdd->setGeometry(QRect(750, 110, 61, 31));
        cmdSubLangDel = new QPushButton(tbMaterials);
        cmdSubLangDel->setObjectName(QStringLiteral("cmdSubLangDel"));
        cmdSubLangDel->setGeometry(QRect(830, 110, 61, 31));
        sbMaterialPrice = new QSpinBox(tbMaterials);
        sbMaterialPrice->setObjectName(QStringLiteral("sbMaterialPrice"));
        sbMaterialPrice->setGeometry(QRect(370, 70, 141, 31));
        sbMaterialPrice->setMaximum(999999999);
        lblMaterialCreated = new QLabel(tbMaterials);
        lblMaterialCreated->setObjectName(QStringLiteral("lblMaterialCreated"));
        lblMaterialCreated->setGeometry(QRect(920, 20, 141, 31));
        lblMaterialAnswer = new QLabel(tbMaterials);
        lblMaterialAnswer->setObjectName(QStringLiteral("lblMaterialAnswer"));
        lblMaterialAnswer->setGeometry(QRect(1110, 20, 111, 31));
        cmdMaterialClear = new QPushButton(tbMaterials);
        cmdMaterialClear->setObjectName(QStringLiteral("cmdMaterialClear"));
        cmdMaterialClear->setGeometry(QRect(10, 500, 381, 61));
        cmdMaterialDel = new QPushButton(tbMaterials);
        cmdMaterialDel->setObjectName(QStringLiteral("cmdMaterialDel"));
        cmdMaterialDel->setGeometry(QRect(420, 500, 381, 61));
        cmdMaterialCreate = new QPushButton(tbMaterials);
        cmdMaterialCreate->setObjectName(QStringLiteral("cmdMaterialCreate"));
        cmdMaterialCreate->setGeometry(QRect(840, 500, 381, 61));
        sbMaterialRuntime = new QSpinBox(tbMaterials);
        sbMaterialRuntime->setObjectName(QStringLiteral("sbMaterialRuntime"));
        sbMaterialRuntime->setGeometry(QRect(370, 120, 141, 31));
        sbMaterialRuntime->setMaximum(1000);
        cmdExtraLanguageTracksDel = new QPushButton(tbMaterials);
        cmdExtraLanguageTracksDel->setObjectName(QStringLiteral("cmdExtraLanguageTracksDel"));
        cmdExtraLanguageTracksDel->setGeometry(QRect(220, 360, 61, 31));
        lstExtraLanguageTracks = new QListWidget(tbMaterials);
        lstExtraLanguageTracks->setObjectName(QStringLiteral("lstExtraLanguageTracks"));
        lstExtraLanguageTracks->setGeometry(QRect(10, 400, 271, 81));
        cbExtraLanguageTracks = new QComboBox(tbMaterials);
        cbExtraLanguageTracks->setObjectName(QStringLiteral("cbExtraLanguageTracks"));
        cbExtraLanguageTracks->setGeometry(QRect(10, 360, 111, 31));
        cmdExtraLanguageTracksAdd = new QPushButton(tbMaterials);
        cmdExtraLanguageTracksAdd->setObjectName(QStringLiteral("cmdExtraLanguageTracksAdd"));
        cmdExtraLanguageTracksAdd->setGeometry(QRect(140, 360, 61, 31));
        cbExtraSubtitleTracks = new QComboBox(tbMaterials);
        cbExtraSubtitleTracks->setObjectName(QStringLiteral("cbExtraSubtitleTracks"));
        cbExtraSubtitleTracks->setGeometry(QRect(310, 360, 121, 31));
        cmdExtraSubtitleTracksAdd = new QPushButton(tbMaterials);
        cmdExtraSubtitleTracksAdd->setObjectName(QStringLiteral("cmdExtraSubtitleTracksAdd"));
        cmdExtraSubtitleTracksAdd->setGeometry(QRect(450, 360, 61, 31));
        lstExtraSubtitleTracks = new QListWidget(tbMaterials);
        lstExtraSubtitleTracks->setObjectName(QStringLiteral("lstExtraSubtitleTracks"));
        lstExtraSubtitleTracks->setGeometry(QRect(310, 400, 281, 81));
        cmdExtraSubtitleTracksDel = new QPushButton(tbMaterials);
        cmdExtraSubtitleTracksDel->setObjectName(QStringLiteral("cmdExtraSubtitleTracksDel"));
        cmdExtraSubtitleTracksDel->setGeometry(QRect(530, 360, 61, 31));
        cmdBonusFeaturesAdd = new QPushButton(tbMaterials);
        cmdBonusFeaturesAdd->setObjectName(QStringLiteral("cmdBonusFeaturesAdd"));
        cmdBonusFeaturesAdd->setGeometry(QRect(750, 360, 61, 31));
        lstBonusFeatures = new QListWidget(tbMaterials);
        lstBonusFeatures->setObjectName(QStringLiteral("lstBonusFeatures"));
        lstBonusFeatures->setGeometry(QRect(620, 400, 271, 81));
        cmdBonusFeaturesDel = new QPushButton(tbMaterials);
        cmdBonusFeaturesDel->setObjectName(QStringLiteral("cmdBonusFeaturesDel"));
        cmdBonusFeaturesDel->setGeometry(QRect(830, 360, 61, 31));
        lblExtraLanguageTracks = new QLabel(tbMaterials);
        lblExtraLanguageTracks->setObjectName(QStringLiteral("lblExtraLanguageTracks"));
        lblExtraLanguageTracks->setGeometry(QRect(10, 320, 171, 31));
        lblExtraSubtitleTracks = new QLabel(tbMaterials);
        lblExtraSubtitleTracks->setObjectName(QStringLiteral("lblExtraSubtitleTracks"));
        lblExtraSubtitleTracks->setGeometry(QRect(310, 320, 171, 31));
        lblBonusFeatures = new QLabel(tbMaterials);
        lblBonusFeatures->setObjectName(QStringLiteral("lblBonusFeatures"));
        lblBonusFeatures->setGeometry(QRect(620, 320, 171, 31));
        lblFirstSideContent = new QLabel(tbMaterials);
        lblFirstSideContent->setObjectName(QStringLiteral("lblFirstSideContent"));
        lblFirstSideContent->setGeometry(QRect(10, 270, 151, 31));
        txtFirstSideContent = new QLineEdit(tbMaterials);
        txtFirstSideContent->setObjectName(QStringLiteral("txtFirstSideContent"));
        txtFirstSideContent->setGeometry(QRect(160, 270, 241, 31));
        lblSecondSideContent = new QLabel(tbMaterials);
        lblSecondSideContent->setObjectName(QStringLiteral("lblSecondSideContent"));
        lblSecondSideContent->setGeometry(QRect(460, 270, 181, 31));
        txtSecondSideContent = new QLineEdit(tbMaterials);
        txtSecondSideContent->setObjectName(QStringLiteral("txtSecondSideContent"));
        txtSecondSideContent->setGeometry(QRect(650, 270, 241, 31));
        txtBonusFeatures = new QLineEdit(tbMaterials);
        txtBonusFeatures->setObjectName(QStringLiteral("txtBonusFeatures"));
        txtBonusFeatures->setGeometry(QRect(620, 360, 111, 31));
        sbFrameHorizontal = new QSpinBox(tbMaterials);
        sbFrameHorizontal->setObjectName(QStringLiteral("sbFrameHorizontal"));
        sbFrameHorizontal->setGeometry(QRect(1110, 370, 111, 31));
        sbFrameVertical = new QSpinBox(tbMaterials);
        sbFrameVertical->setObjectName(QStringLiteral("sbFrameVertical"));
        sbFrameVertical->setGeometry(QRect(1110, 410, 111, 31));
        lblMaterialFrameVertical = new QLabel(tbMaterials);
        lblMaterialFrameVertical->setObjectName(QStringLiteral("lblMaterialFrameVertical"));
        lblMaterialFrameVertical->setGeometry(QRect(920, 410, 161, 31));
        lblMaterialFrameAspect = new QLabel(tbMaterials);
        lblMaterialFrameAspect->setObjectName(QStringLiteral("lblMaterialFrameAspect"));
        lblMaterialFrameAspect->setGeometry(QRect(920, 320, 161, 31));
        txtFrameDescription = new QLineEdit(tbMaterials);
        txtFrameDescription->setObjectName(QStringLiteral("txtFrameDescription"));
        txtFrameDescription->setGeometry(QRect(1110, 450, 113, 31));
        lblMaterialFrameDescription = new QLabel(tbMaterials);
        lblMaterialFrameDescription->setObjectName(QStringLiteral("lblMaterialFrameDescription"));
        lblMaterialFrameDescription->setGeometry(QRect(920, 450, 181, 31));
        lblMaterialPackageMaterial = new QLabel(tbMaterials);
        lblMaterialPackageMaterial->setObjectName(QStringLiteral("lblMaterialPackageMaterial"));
        lblMaterialPackageMaterial->setGeometry(QRect(920, 120, 151, 31));
        lblMaterialPackageHeight = new QLabel(tbMaterials);
        lblMaterialPackageHeight->setObjectName(QStringLiteral("lblMaterialPackageHeight"));
        lblMaterialPackageHeight->setGeometry(QRect(920, 160, 151, 31));
        lblMaterialPackageDepth = new QLabel(tbMaterials);
        lblMaterialPackageDepth->setObjectName(QStringLiteral("lblMaterialPackageDepth"));
        lblMaterialPackageDepth->setGeometry(QRect(920, 240, 151, 31));
        sbPackagingHeight = new QSpinBox(tbMaterials);
        sbPackagingHeight->setObjectName(QStringLiteral("sbPackagingHeight"));
        sbPackagingHeight->setGeometry(QRect(1110, 160, 111, 31));
        sbPackagingDepth = new QSpinBox(tbMaterials);
        sbPackagingDepth->setObjectName(QStringLiteral("sbPackagingDepth"));
        sbPackagingDepth->setGeometry(QRect(1110, 240, 111, 31));
        lblMaterialPackageWidth = new QLabel(tbMaterials);
        lblMaterialPackageWidth->setObjectName(QStringLiteral("lblMaterialPackageWidth"));
        lblMaterialPackageWidth->setGeometry(QRect(920, 200, 151, 31));
        sbPackagingWidth = new QSpinBox(tbMaterials);
        sbPackagingWidth->setObjectName(QStringLiteral("sbPackagingWidth"));
        sbPackagingWidth->setGeometry(QRect(1110, 200, 111, 31));
        cbPackagingMaterial = new QComboBox(tbMaterials);
        cbPackagingMaterial->setObjectName(QStringLiteral("cbPackagingMaterial"));
        cbPackagingMaterial->setGeometry(QRect(1110, 120, 111, 31));
        sbComboSingleDVD = new QSpinBox(tbMaterials);
        sbComboSingleDVD->setObjectName(QStringLiteral("sbComboSingleDVD"));
        sbComboSingleDVD->setGeometry(QRect(760, 70, 131, 31));
        lblComboDoubleDVD = new QLabel(tbMaterials);
        lblComboDoubleDVD->setObjectName(QStringLiteral("lblComboDoubleDVD"));
        lblComboDoubleDVD->setGeometry(QRect(530, 120, 261, 31));
        sbComboDoubleDVD = new QSpinBox(tbMaterials);
        sbComboDoubleDVD->setObjectName(QStringLiteral("sbComboDoubleDVD"));
        sbComboDoubleDVD->setGeometry(QRect(760, 120, 131, 31));
        lblComboSingleDVD = new QLabel(tbMaterials);
        lblComboSingleDVD->setObjectName(QStringLiteral("lblComboSingleDVD"));
        lblComboSingleDVD->setGeometry(QRect(530, 120, 271, 31));
        tabWidget->addTab(tbMaterials, QString());
        lblProjectName = new QLabel(ProjectDetails);
        lblProjectName->setObjectName(QStringLiteral("lblProjectName"));
        lblProjectName->setGeometry(QRect(50, 0, 271, 31));
        QFont font1;
        font1.setPointSize(18);
        font1.setBold(true);
        font1.setWeight(75);
        lblProjectName->setFont(font1);

        retranslateUi(ProjectDetails);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(ProjectDetails);
    } // setupUi

    void retranslateUi(QDialog *ProjectDetails)
    {
        ProjectDetails->setWindowTitle(QApplication::translate("ProjectDetails", "Dialog", Q_NULLPTR));
        cmdLocationDel->setText(QApplication::translate("ProjectDetails", "Delete", Q_NULLPTR));
        cmdLocationAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        cbLanguage->setCurrentText(QString());
        cmdClearGeneralChanges->setText(QApplication::translate("ProjectDetails", "Reset Changes", Q_NULLPTR));
        lblRuntime->setText(QApplication::translate("ProjectDetails", "Runtime:", Q_NULLPTR));
        lblSummary->setText(QApplication::translate("ProjectDetails", "Summary:", Q_NULLPTR));
        lblLocations->setText(QApplication::translate("ProjectDetails", "Locations:", Q_NULLPTR));
        cmdApplyGeneralChanges->setText(QApplication::translate("ProjectDetails", "Update Project Details", Q_NULLPTR));
        lblGenre->setText(QApplication::translate("ProjectDetails", "Genre:", Q_NULLPTR));
        lblStatus->setText(QApplication::translate("ProjectDetails", "Status:", Q_NULLPTR));
        lblRelease->setText(QApplication::translate("ProjectDetails", "Release:", Q_NULLPTR));
        lblTitleProjects->setText(QApplication::translate("ProjectDetails", "Title:", Q_NULLPTR));
        lblLanguage->setText(QApplication::translate("ProjectDetails", "Language:", Q_NULLPTR));
        lblKeywords->setText(QApplication::translate("ProjectDetails", "Keywords:", Q_NULLPTR));
        lblSales->setText(QApplication::translate("ProjectDetails", "Sales:", Q_NULLPTR));
        cmdKeywordsDel->setText(QApplication::translate("ProjectDetails", "Delete", Q_NULLPTR));
        cmdKeywordsAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tbGeneral), QApplication::translate("ProjectDetails", "General", Q_NULLPTR));
        cmdCrewFilter->setText(QApplication::translate("ProjectDetails", "Filter", Q_NULLPTR));
        cmdCrewDel->setText(QApplication::translate("ProjectDetails", "Delete", Q_NULLPTR));
        cmdCrewAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        lblDateOfBirth->setText(QApplication::translate("ProjectDetails", "Date of Birth:", Q_NULLPTR));
        lblIDNum->setText(QApplication::translate("ProjectDetails", "ID:", Q_NULLPTR));
        lblNameTitle->setText(QApplication::translate("ProjectDetails", "Title:", Q_NULLPTR));
        lblExperience->setText(QApplication::translate("ProjectDetails", "Experience: ", Q_NULLPTR));
        lblName->setText(QApplication::translate("ProjectDetails", "Name:", Q_NULLPTR));
        lblCrewLocations->setText(QApplication::translate("ProjectDetails", "Locations:", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tbCrew), QApplication::translate("ProjectDetails", "Crew", Q_NULLPTR));
        lblMaterialType->setText(QApplication::translate("ProjectDetails", "Type of Material: ", Q_NULLPTR));
        lblMaterialIDNum->setText(QApplication::translate("ProjectDetails", "ID Number:", Q_NULLPTR));
        lblMaterialTitle->setText(QApplication::translate("ProjectDetails", "Title:", Q_NULLPTR));
        lblVFormat->setText(QApplication::translate("ProjectDetails", "Video Format:", Q_NULLPTR));
        lblAFormat->setText(QApplication::translate("ProjectDetails", "Audio Format:", Q_NULLPTR));
        lblMaterialLanguage->setText(QApplication::translate("ProjectDetails", "Language:", Q_NULLPTR));
        lblMaterialFrameHorizontal->setText(QApplication::translate("ProjectDetails", "Frame Horizontal Ratio:", Q_NULLPTR));
        lblMaterialPackage->setText(QApplication::translate("ProjectDetails", "Packaging:", Q_NULLPTR));
        lblMaterialRuntime->setText(QApplication::translate("ProjectDetails", "Runtime:", Q_NULLPTR));
        lblMaterialPrice->setText(QApplication::translate("ProjectDetails", "Price:", Q_NULLPTR));
        lblMaterialSubLang->setText(QApplication::translate("ProjectDetails", "Subtitle Languages:", Q_NULLPTR));
        cmdSubLangAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        cmdSubLangDel->setText(QApplication::translate("ProjectDetails", "Del", Q_NULLPTR));
        lblMaterialCreated->setText(QApplication::translate("ProjectDetails", "Material Created:", Q_NULLPTR));
        lblMaterialAnswer->setText(QApplication::translate("ProjectDetails", "No", Q_NULLPTR));
        cmdMaterialClear->setText(QApplication::translate("ProjectDetails", "Clear Changes", Q_NULLPTR));
        cmdMaterialDel->setText(QApplication::translate("ProjectDetails", "Delete Material", Q_NULLPTR));
        cmdMaterialCreate->setText(QApplication::translate("ProjectDetails", "Create Material", Q_NULLPTR));
        cmdExtraLanguageTracksDel->setText(QApplication::translate("ProjectDetails", "Del", Q_NULLPTR));
        cmdExtraLanguageTracksAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        cmdExtraSubtitleTracksAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        cmdExtraSubtitleTracksDel->setText(QApplication::translate("ProjectDetails", "Del", Q_NULLPTR));
        cmdBonusFeaturesAdd->setText(QApplication::translate("ProjectDetails", "Add", Q_NULLPTR));
        cmdBonusFeaturesDel->setText(QApplication::translate("ProjectDetails", "Del", Q_NULLPTR));
        lblExtraLanguageTracks->setText(QApplication::translate("ProjectDetails", "Extra Language Tracks:", Q_NULLPTR));
        lblExtraSubtitleTracks->setText(QApplication::translate("ProjectDetails", "Extra Subtitle Tracks:", Q_NULLPTR));
        lblBonusFeatures->setText(QApplication::translate("ProjectDetails", "Bonus Features:", Q_NULLPTR));
        lblFirstSideContent->setText(QApplication::translate("ProjectDetails", "First Side Content:", Q_NULLPTR));
        lblSecondSideContent->setText(QApplication::translate("ProjectDetails", "Second Side Content:", Q_NULLPTR));
        lblMaterialFrameVertical->setText(QApplication::translate("ProjectDetails", "Frame Vertical Ratio:", Q_NULLPTR));
        lblMaterialFrameAspect->setText(QApplication::translate("ProjectDetails", "Frame Aspect:", Q_NULLPTR));
        lblMaterialFrameDescription->setText(QApplication::translate("ProjectDetails", "Frame Ratio Description:", Q_NULLPTR));
        lblMaterialPackageMaterial->setText(QApplication::translate("ProjectDetails", "Packaging Material:", Q_NULLPTR));
        lblMaterialPackageHeight->setText(QApplication::translate("ProjectDetails", "Packaging Height:", Q_NULLPTR));
        lblMaterialPackageDepth->setText(QApplication::translate("ProjectDetails", "Packaging Depth:", Q_NULLPTR));
        lblMaterialPackageWidth->setText(QApplication::translate("ProjectDetails", "Packaging Width:", Q_NULLPTR));
        lblComboDoubleDVD->setText(QApplication::translate("ProjectDetails", "Amount of Double Sided DVDs:", Q_NULLPTR));
        lblComboSingleDVD->setText(QApplication::translate("ProjectDetails", "Amount of Single Sided DVDs:", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tbMaterials), QApplication::translate("ProjectDetails", "Materials", Q_NULLPTR));
        lblProjectName->setText(QApplication::translate("ProjectDetails", "Project Name", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ProjectDetails: public Ui_ProjectDetails {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROJECTDETAILS_H
